swagger: '2.0'
info:
  version: v2
  title: User transaction
  description: Transaction API for argent Back OCR project 13
  termsOfService: None
  contact:
    name: Raphael parodi
    url: https://inexpensive-chipmunk-220.notion.site/Rapha-l-Parodi-6d28e8e66ba0490e8da5433b474645d8
    email: raficraft@gmail.com
basePath: /
paths:
  /api/v1/user/transaction:
     post:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /api/v1/user/transaction/details:
     post:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/BodyTransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/TransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /api/v1/user/transaction/edit/category:
     put:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/BodyEditTransactionCategory'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/EditTransactionCategory'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
          
  /api/v1/user/transaction/edit/notes:
     put:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/BodyEditTransactionNote'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/EditTransactionNote'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
            
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header 

definitions:
  Transactions:
    type: object
    description : transaction lists for the current month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description : id of transaction
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: string
            description: transaction amount($)
          balance:
            type: string
            description: balance ($)
            
  BodyTransactionsDetails :
    type: object
    description : transaction lists for the current month
    properties :
      id :
        type : integer
        description : id of transaction
            
  TransactionsDetails:
    type: object
    description : transaction lists for the current month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
           id:
            type: string
            description : id of transaction
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: string
            description: transaction amount($)
          balance:
            type: string
            description: balance ($)
          transaction type:
            type: string
            description: type of transaction
          category:
            type: string
            description: category of transaction
          notes:
            type: string
            description: notes of transaction
            
  BodyEditTransactionCategory : 
    type: object
    description : Edit category of transaction
    properties :
        id :
          type : integer
          description : id of transaction
        category :
          type : string
          description: category of transaction
  
  EditTransactionCategory :
    type: object
    description : Api response
    properties:
        status:
          type: integer
        message:
          type: string
          
  BodyEditTransactionNote : 
    type: object
    description : Edit notes of transaction
    properties :
        id :
          type : integer
          description : id of transaction
        category :
          type : string
          description: notes of transaction
  
  EditTransactionNote :
    type: object
    description : Api response
    properties:
        status:
          type: integer
        message:
          type: string        

        
  
 

